**GEOMETRICAL INTUITION OF MULTIPLE LINEAR REGRESSION**

In [39]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

import warnings
warnings.filterwarnings("ignore")

In [40]:
inc=pd.read_csv('income.csv')

In [41]:
inc.head()

   age  experience  income
0   25           1   30450
1   30           3   35670
2   47           2   31580
3   32           5   40130
4   43          10   47830

In [42]:
px.scatter_3d(inc,x='age',y='experience',z='income')

In [43]:
X=inc[['age','experience']]
y=inc['income']

In [44]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.4,random_state=3)

In [45]:
from sklearn.linear_model import LinearRegression

In [46]:
lr=LinearRegression()

In [47]:
lr.fit(X_train,y_train)

LinearRegression()

In [65]:
X_test.head()

    age  experience
31   36          14
11   47           9
53   20           1
27   37          18
12   54           5

In [49]:
X_test.iloc[[0]]

    age  experience
31   36          14

In [51]:
lr.predict(X_test.iloc[[0]])

array([62979.67533132])

In [52]:
# y=B0+B1X1+B2X2
lr.coef_  # gives B1 and B2

array([  44.63589723, 2896.87028045])

In [ ]:
lr.intercept_   # gives B0

np.float64(20816.599104781635)

**PLOTTING PLANE WHICH IS OUR FINAL RESULT LIKE LINE IN SIMPLE LR**

In [63]:
# create grid
x = np.linspace(inc['age'].min(), inc['age'].max(), 10)
y = np.linspace(inc['experience'].min(), inc['experience'].max(), 10)

xGrid, yGrid = np.meshgrid(x, y)

# create feature matrix
final = np.vstack((xGrid.ravel(), yGrid.ravel())).T

# predict values
z = lr.predict(final).reshape(10,10)

# scatter plot
fig = px.scatter_3d(inc, x='age', y='experience', z='income')

# regression plane
fig.add_trace(go.Surface(x=xGrid, y=yGrid, z=z, opacity=0.6))

fig.show()